excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cbates87.github.io
title: Musings of a Techno-Geek
tagline: Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important. - Bill Gates
description: My thoughts on educational technology and  current trends.
paginate: 5